version: '3'

services:
  db:
    image: mongo:5.0.0
    restart: always
    container_name: db-mongo-cqrs
    ports:
      - 27016:27017
    environment:
       MONGODB_DATABASE: nest-cqrs
    volumes:
      - ./mongo:/data/db
